#sudo: false
language: ruby
branches:
    only:
        - master
install:
    - sudo add-apt-repository ppa:texlive-backports/ppa -y
    - sudo apt-get update -y
    - sudo apt-get install texlive-latex-extra -y 
    - sudo apt-get install texlive-luatex -y
    - sudo apt-get install texlive-fonts-extra -y
    - sudo apt-get install cm-super -y
    - sudo apt-get install texlive-bibtex-extra -y
    - sudo apt-get install latexmk -y
    - sudo apt-get install tex4ht -y
    - wget http://tug.org/fonts/getnonfreefonts/install-getnonfreefonts
    - sudo texlua install-getnonfreefonts
    - sudo getnonfreefonts-sys garamond
#addons:
    #apt:
        #sources: 
            #- ppa:texlive-backports/ppa
        #packages:
            #-texlive-latex-extra
            #-texlive-luatex
            #-texlive-fonts-extra
            #-cm-super
            #-texlive-bibtex-extra
            #-latexmk
            #-tex4ht
#install:
    #- wget http://tug.org/fonts/getnonfreefonts/install-getnonfreefonts
    #- texlua install-getnonfreefonts
    #- getnonfreefonts garamond
script: 
    - latexmk
    - latexmk -pdf
after_success:
    - git config --global user.email ${GIT_EMAIL}
    - git config --global user.name ${GIT_NAME}
    - git clone --quiet --branch=travis-build https://${GH_TOKEN}@github.com/johntfoster/CV travis-build > /dev/null
    - cd travis-build
    - cp -f $HOME/build/johntfoster/CV/cv.pdf .
    - cp -f $HOME/build/johntfoster/CV/cv.html .
    - git add cv.pdf cv.html
    - git commit -m "Travis CI autocommit from travis build ${TRAVIS_BUILD_NUMBER}"
    - git push -fq origin travis-build > /dev/null
    - gem install travis
    - travis restart -r johnfoster-pge-utexas/johnfoster-pge-utexas.github.io --token ${TRAVIS_TOKEN} --skip-completion-check


